### PR TITLE
Kern 3101 - Additional Pooled Content Load Test Scripts

### PR DESCRIPTION
**Pull request by dgillman**
Added tests around pooled content. I have PR'd this to mrvisser's repository, but thought I should PR to yours as well to limit divergence. If you have any advice or comments on the tests I've created/pushed, I'd love your perspective.

Thanks,
D

### CODE REVIEW

**Comment by kcampos** [comment]
Hmm, can't automatically merge this. rebase needed?

**Comment by dgillman** [comment]
Hmm... yeah, I based it off of Branden's repo. Let me see what I can do.

-D

---

Duffy Gillman
Sr. Software Engineer
The rSmart Group, Inc.

**Comment by dgillman** [comment]
@kcampos I'm going to close this pull request now.

🤣

**Comment by kcampos** [comment]
Hahaha. I was just getting to this though!

--
Kyle Campos
Twitter: @kcampos

**Pull request closed without merging**
